exp_name: "HSI reconstruction"
is_debug: True
seed: 42

camera:
  lens_file: "./lenses/paraxiallens/doelens_hsi.json"
  sensor_file: "./sensors/example_sensor.json"

network:
  name: NAFNet
  in_chan: 3
  out_chan: 31
  width: 32
  middle_blk_num: 1
  enc_blk_nums: [1, 1, 1, 18]
  dec_blk_nums: [1, 1, 1, 1]
  ckpt_path: null

train:
  epochs: 100
  eval_every_n_epochs: 5
  log_every_n_steps: 100
  lr: 1e-4

train_set:
  dataset: "./datasets/cave_train.txt"
  crop_size: [256, 256]
  # output_type: "rggbi"
  batch_size: 1
  num_workers: 3

eval_set:
  dataset: "./datasets/cave_val.txt"
  crop_size: [512, 512]
  # output_type: "rggbi"
  batch_size: 1
  num_workers: 3